travis:
  secure:
    BINSTAR_TOKEN: rjuCzxMWX3kqH0g7WWFAAOwfrETod8eak88DXvQ7JrMPiYmoGd3vngOYuT4dXn5omH7Tw3C24oiGrSKeFC6gN1/gv+oohzyqgPQwtGwMTDyh88mLar/Zfm5EA/jshNgkFUGObPQ4xIUB2nXPH1gqz00SRb63ysrInX+jY9Hmzu4E0NSD17Zj3koYidxgZEJ7XA49IWkY4bSxAz37bSV+YNDxfNh2OY1ISmrBJHwp8FU1ap0Yxv7mkzIChXTrvpWIkAw2edPCunnuU1q9z40W/GCXsWLIJ2FiIzQaWeBC2350tUUDycIu/eYjdRaU7I2dBmsYw0NLOgj9MKJZtmVGoHcX6qhDD0/WY2VdPMcSAJ9DwVkK7TZEeEsFvWQXx3gWwy33WhuLGjLl1oltPFzf3TBg8h9YsW9XcDZRqz1DLPNkFFpSP+LujAKv4B1P9U1qo2pM38jzWVNKkzElcSaZvy7cPsrfln3pMuoZmm+SV96W4u+b9U4btcY5LwngnReCXURZ0LCDK0S4+L1Oqp1ooKvNIlmyKmL2CGPjrwgwkiaZIII1rd6Fa/zj8IhiDgrcJZabeGdOFkM1DKvwc/+a4U0vQqcDquC+0wiPNsVZO+1KHqoOTI35Kv/mjCOuE/9ZQw3ZHOXa2HLlV9csvbyoFNMUbhm5BGb6IaGlE9cuurM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
